config/routes.rb
Rails.application.routes.draw do
  resources :notes

  get '/cash_transactions/income', to: 'cash_transactions#new'
  post '/cash_transactions/income', to: 'cash_transactions#income'

  get '/cash_transactions/expence', to: 'cash_transactions#new'
  post '/cash_transactions/expence', to: 'cash_transactions#expence'

  get '/cash_transactions/choose_type', to: 'cash_transactions#choose_type'
  get '/cash_transactions/important_transaction', to: 'cash_transactions#important_transaction', as: 'important_transaction'
  resources :cash_transactions
  get 'errors/not_found'
  resources :finance
  resources :people
  get 'home/index'
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root 'home#index'

  get '/404', to: 'errors#not_found'

  post '/people/new', to: 'people#create'
  post '/people/:id/edit', to: 'people#update'

  get '/finances', to: 'finance#index'

  get '/finance/:id/edit', to: 'finance#edit'
  post '/finance/:id/edit', to: 'finance#update'

  get '/finance/new', to: 'finance#new'
  post '/finance/new', to: 'finance#create'

  get '/people/:id/finances', to: 'people#persons_finances', as: 'people_persons_finances'

  get '/finances/:id/finance_info', to: 'finance#finance_info', as: 'finance_info'
  post '/finances/:id/finance_info', to: 'finance#finance_info'

  get '/cash_transactions', to: 'cash_transactions#index'

  get '/cash_transactions/:id/edit', to: 'cash_transactions#edit'
  post '/cash_transactions/:id/edit', to: 'cash_transactions#update'

  get '/note/:id/show', to: 'notes#show', as: 'notes_show'
  get '/note/:id/edit', to: 'notes#edit'
  post '/note/:id/edit', to: 'notes#edit'
  get 'note/:id/new', to: 'notes#new'
  post 'note/:id/new', to: 'notes#create'

  get '/charts', to: 'charts#index'
  post '/charts', to: 'charts#index'

end

app/models/note.rb
# frozen_string_literal: true

class Note < ApplicationRecord
  belongs_to :cash_transaction, optional: true
  validates :note_text, presence: true, length: { maximum: 100 }
end

app/controllers/notes_controller.rb
# frozen_string_literal: true

class NotesController < ApplicationController
  before_action :find_note, only: %i[show edit update destroy]

  # GET /notes or /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1 or /notes/1.json
  def show
    @note = Note.find_by(id: params[:id])
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit; end

  # POST /notes or /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to cash_transactions_path, notice: 'Note was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1 or /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1 or /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def find_note
    @note = Note.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def note_params
    params.require(:note).permit(:note_text, :id)
  end
end

def require_same_user
  cash_transaction = CashTransaction.find_by_note_id(params[:id])
  return if current_user == cash_transaction.persons_finance.person.user

  flash[:alert] = 'You can\'t do this'
  redirect_to root_path
end

app/views/notes/_form.html.erb
<div class="card">
<%= form_with(model: note) do |form| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
        <% note.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    <div class="card-body">
      <div class="card-body">
  <div class="field form-group">
    <%= form.label 'Enter the note text' %>
    <%= form.text_field :note_text, class:"form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "Create note", class: 'btn btn-secondary' %>
  </div>
<% end %>
  </div>
  </div>
</div>

app/views/notes/edit.html.erb
<h1>Editing Note</h1>
<%= render 'form', note: @note %>
<br>
<%= link_to 'Show', @note, class:'btn btn-light' %>
<%= link_to 'Back', finance_info_path, class:'btn btn-light' %>

app/views/notes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notes</h1>

<table>
  <thead>
    <tr>
      <th>Note text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= note.note_text %></td>
        <td><%= link_to 'Show', note %></td>
        <td><%= link_to 'Edit', edit_note_path(note) %></td>
        <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Note', new_note_path %>

app/views/notes/new.html.erb
<h2>You don't have a note for this transaction. Create it</h2>

<%= render 'form', note: @note %>

<%= link_to 'Back', cash_transactions_path %>

app/views/notes/note_not_found.html.erb
<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<p>
  <strong>Note text:</strong>
  <%= @note.note_text %>
</p>

<%= link_to 'Edit', edit_note_path(@note), class:'btn btn-light' %>
<%= link_to 'Back', finance_info_path, class:'btn btn-light' %>