config/routes.rb
Rails.application.routes.draw do
  resources :notes

  get '/cash_transactions/income', to: 'cash_transactions#new'
  post '/cash_transactions/income', to: 'cash_transactions#income'

  get '/cash_transactions/expence', to: 'cash_transactions#new'
  post '/cash_transactions/expence', to: 'cash_transactions#expence'

  get '/cash_transactions/choose_type', to: 'cash_transactions#choose_type'
  get '/cash_transactions/important_transaction', to: 'cash_transactions#important_transaction', as: 'important_transaction'
  resources :cash_transactions
  get 'errors/not_found'
  resources :finance
  resources :people
  get 'home/index'
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root 'home#index'

  get '/404', to: 'errors#not_found'

  post '/people/new', to: 'people#create'
  post '/people/:id/edit', to: 'people#update'

  get '/finances', to: 'finance#index'

  get '/finance/:id/edit', to: 'finance#edit'
  post '/finance/:id/edit', to: 'finance#update'

  get '/finance/new', to: 'finance#new'
  post '/finance/new', to: 'finance#create'

  get '/people/:id/finances', to: 'people#persons_finances', as: 'people_persons_finances'

  get '/finances/:id/finance_info', to: 'finance#finance_info', as: 'finance_info'
  post '/finances/:id/finance_info', to: 'finance#finance_info'

  get '/cash_transactions', to: 'cash_transactions#index'

  get '/cash_transactions/:id/edit', to: 'cash_transactions#edit'
  post '/cash_transactions/:id/edit', to: 'cash_transactions#update'

  get '/note/:id/show', to: 'notes#show', as: 'notes_show'
  get '/note/:id/edit', to: 'notes#edit'
  post '/note/:id/edit', to: 'notes#edit'
  get 'note/:id/new', to: 'notes#new'
  post 'note/:id/new', to: 'notes#create'

  get '/charts', to: 'charts#index'
  post '/charts', to: 'charts#index'

end

app/models/person.rb
# frozen_string_literal: true

class Person < ApplicationRecord
  validates :first_name, presence: true, length: { minimum: 3, maximum: 20 }
  validates :last_name, presence: true, length: { minimum: 3, maximum: 20 }
  validates :type_name, presence: true, length: { minimum: 2, maximum: 20 }

  belongs_to :user
  has_many :persons_finances
  has_many :finances, through: :persons_finances
  after_create :create_finance

  def create_finance
    finance = Finance.new(name: 'New finance', incomeOrExpence: true)
    finance.people << self
    finance.save
  end

  def destroy
    return false if user.person.count == 1
  end
end

app/controllers/people_controller.rb
# frozen_string_literal: true

class PeopleController < ApplicationController
  before_action :find_person, only: %i[show edit update destroy persons_finances]
  before_action :require_same_user, only: %i[destroy edit update]
  before_action :find_finance, only: %i[show edit update destroy persons_finances]

  # GET /people or /people.json
  def index
    @people = current_user.person
  end

  # GET /people/1 or /people/1.json
  def show; end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit; end

  # POST /people or /people.json
  def create
    @person = Person.new(person_params)
    @person.user = current_user
    if @person.save
      flash[:notice] = 'Person was successfully created.'
      redirect_to people_path
    else
      render :new
    end
  end

  # PATCH/PUT /people/1 or /people/1.json
  def update
    if @person.update(person_params)
      flash[:notice] = 'Person updated successfully'
      redirect_to people_path
    else
      render :edit
    end
  end

  # DELETE /people/1 or /people/1.json
  def destroy
    if @person.destroy
      flash[:notice] = 'Person deleted successfully'
    else
      flash[:alert] = 'You can\'t do this. It\'s your last person'
    end
    redirect_to people_path
  end

  def find_person
    if Person.exists?(params[:id])
      @person = Person.find(params[:id])
    else
      redirect_to errors_not_found_path
    end
  end

  def persons_finances; end

  private

  # Use callbacks to share common setup or constraints between actions.

  def find_finance
    if Finance.exists?(params[:id])
      @finances = find_person.finances
    else
      redirect_to errors_not_found_path
    end
  end

  def require_same_user
    person = Person.find(params[:id])
    return if current_user == person.user

    flash[:alert] = 'You can\'t do this'
    redirect_to root_path
  end

  def first_name
    @person = Person.first_name
  end

  # Only allow a list of trusted parameters through.
  def person_params
    params.require(:person).permit(:first_name, :last_name, :type_name)
  end
end

app/views/people/_form.html.erb
<%= form_with(model: person) do |f| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "errors") %> prohibited this person from being saved:</h2>

      <ul>
        <% person.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="card-body">
    <div class="card-body">
      <div class="field form-group">
        <%= f.label :type_name %>
        <%= f.text_field :type_name,autofocus: true, class:"form-control", placeholder: 'Type' %>
      </div>
      <div class="field form-group">
        <%= f.label :first_name %>
        <%= f.text_field :first_name,autofocus: true, class:"form-control", placeholder: 'First name' %>
      </div>
      <div class="field form-group">
        <%= f.label :last_name %>
        <%= f.text_field :last_name,autofocus: true, class:"form-control", placeholder: 'Last name' %>
      </div>
      <%= f.submit "Create person", class: 'btn btn-secondary'%>
    </div>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person, class:'btn btn-secondary' %> |
<%= link_to 'Back', people_path, class:'btn btn-secondary' %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>
<br>
<%= link_to 'New Person', new_person_path, class:'btn btn-primary' %>
<br>
<br>
<table class="table table-striped">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.first_name %></td>
        <td><%= person.last_name %></td>
        <td><%= person.type_name %></td>
        <td><%#= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person), class:'btn btn-secondary' %></td>
        <td><%#= link_to 'Add finance category', new_finance_path(person) %></td>
        <td><%= link_to 'Show Finances', people_persons_finances_path(person), class:'btn btn-secondary'%></td>
        <td><%= link_to 'Delete', person_path(person), method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger' %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/people/new.html.erb
<div class="card">
  <div class="card-header">
    <h4>Create Person</h4>
  </div>
  <div class="card-body">


    <%= form_for :person do |f| %>

      <div class="card-body">
        <div class="card-body">
          <div class="field form-group">
            <%= f.label :type_name %>
            <%= f.text_field :type_name,autofocus: true, class:"form-control", placeholder: 'Type' %>
          </div>
          <div class="field form-group">
            <%= f.label :first_name %>
            <%= f.text_field :first_name,autofocus: true, class:"form-control", placeholder: 'First name' %>
          </div>
          <div class="field form-group">
            <%= f.label :last_name %>
            <%= f.text_field :last_name,autofocus: true, class:"form-control", placeholder: 'Last name' %>
          </div>
          <%= f.submit "Create person", class: 'btn btn-secondary'%>
        </div>
      </div>
    <% end %>

  </div>
</div>

app/views/people/persons_finances.html.erb
<h2 class="ui center aligned icon header">
  <i class="circular file alternate outline icon"></i>
  Categories of <%= @person.first_name %>

</h2>
<% @finances.each do |finance| %>


  <div class="card">
    <div class="content">
      <div class="card-header"><%= finance.name %> [<%= finance.incomeOrExpence ? 'Income' : 'Expence' %>]</div>

      <div class="center aligned description">
        <p class="card-title">Total amount: N/A</p>
      </div>
    </div>

    <div class="extra content">
      <div class="center aligned author">

        <%=link_to 'Edit',edit_finance_path(finance), class:'btn btn-secondary' %>
        <%=link_to 'Delete', finance_path(finance), method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger'  %>
      </div>
    </div>
  </div>

<% end %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @person.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @person.last_name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @person.type_name %>
</p>

<%= link_to 'Edit', edit_person_path(@person), class:'btn btn-secondary' %> |
<%= link_to 'Back', people_path, class:'btn btn-secondary' %>