config/routes.rb
Rails.application.routes.draw do
  resources :notes

  get '/cash_transactions/income', to: 'cash_transactions#new'
  post '/cash_transactions/income', to: 'cash_transactions#income'

  get '/cash_transactions/expence', to: 'cash_transactions#new'
  post '/cash_transactions/expence', to: 'cash_transactions#expence'

  get '/cash_transactions/choose_type', to: 'cash_transactions#choose_type'
  get '/cash_transactions/important_transaction', to: 'cash_transactions#important_transaction', as: 'important_transaction'
  resources :cash_transactions
  get 'errors/not_found'
  resources :finance
  resources :people
  get 'home/index'
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root 'home#index'

  get '/404', to: 'errors#not_found'

  post '/people/new', to: 'people#create'
  post '/people/:id/edit', to: 'people#update'

  get '/finances', to: 'finance#index'

  get '/finance/:id/edit', to: 'finance#edit'
  post '/finance/:id/edit', to: 'finance#update'

  get '/finance/new', to: 'finance#new'
  post '/finance/new', to: 'finance#create'

  get '/people/:id/finances', to: 'people#persons_finances', as: 'people_persons_finances'

  get '/finances/:id/finance_info', to: 'finance#finance_info', as: 'finance_info'
  post '/finances/:id/finance_info', to: 'finance#finance_info'

  get '/cash_transactions', to: 'cash_transactions#index'

  get '/cash_transactions/:id/edit', to: 'cash_transactions#edit'
  post '/cash_transactions/:id/edit', to: 'cash_transactions#update'

  get '/note/:id/show', to: 'notes#show', as: 'notes_show'
  get '/note/:id/edit', to: 'notes#edit'
  post '/note/:id/edit', to: 'notes#edit'
  get 'note/:id/new', to: 'notes#new'
  post 'note/:id/new', to: 'notes#create'

  get '/charts', to: 'charts#index'
  post '/charts', to: 'charts#index'

end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/views/home/_header.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to 'Finance App', root_path, class:"navbar-brand" %>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">

            <% if user_signed_in? %>
            <li class="nav-item">
                <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"btn btn-outline-danger" %>
            </li>
            <li class="nav-item">
                <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "People", people_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Finances", finances_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Transactions", cash_transactions_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Charts", charts_path, class:"nav-link" %>
            </li>
            <% else %>

            <li class="nav-item">
                <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
            </li>

            <li class="nav-item">
                <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
            </li>
            <% end %>
        </ul>
    </div>
</nav>
</body>
</html>

app/views/home/index.html.erb
<h1>Home</h1>