config/routes.rb
Rails.application.routes.draw do
  resources :notes

  get '/cash_transactions/income', to: 'cash_transactions#new'
  post '/cash_transactions/income', to: 'cash_transactions#income'

  get '/cash_transactions/expence', to: 'cash_transactions#new'
  post '/cash_transactions/expence', to: 'cash_transactions#expence'

  get '/cash_transactions/choose_type', to: 'cash_transactions#choose_type'
  get '/cash_transactions/important_transaction', to: 'cash_transactions#important_transaction', as: 'important_transaction'
  resources :cash_transactions
  get 'errors/not_found'
  resources :finance
  resources :people
  get 'home/index'
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root 'home#index'

  get '/404', to: 'errors#not_found'

  post '/people/new', to: 'people#create'
  post '/people/:id/edit', to: 'people#update'

  get '/finances', to: 'finance#index'

  get '/finance/:id/edit', to: 'finance#edit'
  post '/finance/:id/edit', to: 'finance#update'

  get '/finance/new', to: 'finance#new'
  post '/finance/new', to: 'finance#create'

  get '/people/:id/finances', to: 'people#persons_finances', as: 'people_persons_finances'

  get '/finances/:id/finance_info', to: 'finance#finance_info', as: 'finance_info'
  post '/finances/:id/finance_info', to: 'finance#finance_info'

  get '/cash_transactions', to: 'cash_transactions#index'

  get '/cash_transactions/:id/edit', to: 'cash_transactions#edit'
  post '/cash_transactions/:id/edit', to: 'cash_transactions#update'

  get '/note/:id/show', to: 'notes#show', as: 'notes_show'
  get '/note/:id/edit', to: 'notes#edit'
  post '/note/:id/edit', to: 'notes#edit'
  get 'note/:id/new', to: 'notes#new'
  post 'note/:id/new', to: 'notes#create'

  get '/charts', to: 'charts#index'
  post '/charts', to: 'charts#index'

end

app/models/finance.rb
# frozen_string_literal: true

class Finance < ApplicationRecord
  has_many :persons_finances
  has_many :people, through: :persons_finances

  def show_income_or_expence
    incomeOrExpence ? 'Income' : 'Expense'
  end
end

app/controllers/finance_controller.rb
# frozen_string_literal: true

class FinanceController < ApplicationController
  before_action :finance_find, only: %i[show edit update destroy]
  before_action :require_same_user, only: %i[edit update destroy info]

  def new
    @finance = Finance.new
  end

  def edit; end

  def create
    @finance = Finance.new(finance_params)
    params[:finance][:id].each do |person_id|
      @finance.people << Person.find(person_id) if person_id.present?
    end
    if @finance.save
      flash[:notice] = 'Category created successfully'
      redirect_to finances_path
    else
      render 'new'
    end
  end

  def index
    @finance = current_user.person.collect(&:finances).flatten.uniq
  end

  def destroy
    if @finance.destroy
      flash[:notice] = 'Category deleted successfully'
    else
      flash[:alert] = 'You can\'t do this'
    end
    redirect_to finances_path
  end

  def finance_info
    if empty_params?(params)
      @start_date = Date.today.beginning_of_month
      @end_date = end_of_date(Date.today)
    else
      @start_date = Date.parse(params[:cash_transaction][:start_date])
      @end_date = end_of_date(Date.parse(params[:cash_transaction][:end_date]))
    end
    @finance = Finance.find(params[:id])
    @cash_transactions = cash_transaction_filter(person_finance_of_finance(@finance, @start_date, @end_date))
    @sum_amount = @cash_transactions.inject(0) { |sum, t| sum + t.amount }
  end

  def update
    if @finance.update(finance_params)
      PersonsFinance.where(finance_id: @finance.id)
      add_person_to_finance(@finance)
      flash[:notice] = 'Category updated'
      redirect_to finances_path
    else
      render 'edit'
    end
  end

  private

  def person_finance_of_finance(finance, start_date, end_date)
    PersonsFinance.where(finance_id: finance, created_at: start_date..end_date)
  end

  def cash_transaction_filter(persons_finance)
    filter = CashTransaction.joins('LEFT JOIN "notes" ON "notes"."id" = "cash_transactions"."note_id"')
                            .where(persons_finance_id: persons_finance)
    filter = filter.where.not(note: nil) if !params[:with_note].nil? && (params[:with_note].values[0] == '1')
    filter
  end

  def end_of_date(date)
    date.to_datetime.end_of_day
  end

  def finance_params
    params.require(:finance).permit(:name, :incomeOrExpence)
  end

  def show
    @finance = Finance.find_by(id: params[:id])
  end

  def finance_find
    if Finance.exists?(params[:id])
      @finance = Finance.find(params[:id])
    else
      redirect_to errors_not_found_path
    end
  end

  def empty_params?(params)
    params[:cash_transaction].nil? || params[:cash_transaction][:start_date].nil? ||
      params[:cash_transaction][:start_date].nil?
  end

  def require_same_user
    finance = Finance.find(params[:id])
    return if current_user == finance.people.first.user

    flash[:alert] = 'You can\'t do this'
    redirect_to root_path
  end
end

def add_person_to_finance(_finance)
  params[:finance][:id].each do |person_id|
    @finance.people << Person.find(person_id) if person_id.present?
  end
end

app/views/finance/_financeform.htm.erb
<%= form_with(model: finance) do |f| %>
  <% if finance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(finance.errors.count, "errors") %> prohibited this person from being saved:</h2>

      <ul>
        <% finance.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="card-body">
    <div class="card-body">
      <div class="field form-group">
        <%= f.label :name %>
        <%= f.text_field :name,autofocus: true, class:"form-control", placeholder: 'Type' %>
      </div>
      <div class="field form-group">
        <%= f.label 'Expence' %>
        <%= f.check_box :incomeOrExpence, placeholder: 'Expence' %>
      </div>
      <%= f.submit "Create finance", class: 'btn btn-secondary'%>
    </div>
  </div>
<% end %>

app/views/finance/edit.html.erb
<div class="card">
  <div class="card-header">
    <h4>Edit Finance</h4>
  </div>
  <div class="card-body">


    <%= form_for :finance do |f| %>

      <div class="card-body">
        <div class="card-body">
          <div class="field form-group">
            <%= f.label :name %>
            <%= f.text_field :name,autofocus: true, class:"form-control", placeholder: 'Type' %>
            <div class="field form-group">
              <br>
              <%= f.label 'Income' %>
              <%= f.check_box :incomeOrExpence, placeholder: 'Income' %>
            </div>
            <div class="field form-group">
            <%= f.label 'List of person' %>
            <%= f.collection_select(:id, current_user.person.order(:first_name),:id,:first_name, {:prompt => nil}, {:multiple => true}) %>
          </div>

          <%= f.submit "Create finance", class: 'btn btn-secondary'%>
        </div>
      </div>
    <% end %>

  </div>
</div>
</div>

app/views/finance/finance_info.html.erb
<div class="card-header">
  <h3>Transactions of <%= @finance.name %> between</h3>
  <br>
  <%= form_for :cash_transaction do |f| %>
    <div>
      <p> From:<%= f.date_field :start_date, value: @start_date %>
        To:
        <%= f.date_field :end_date, value: @end_date.to_date %></p>
    </div>
    <div>With note: <%=check_box :with_note, type:'checkbox' %></div>

<br>
    <div>
      <%= f.submit "Search", class: 'btn btn-primary' %>
      <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapse" aria-expanded="false" aria-controls="collapseExample">
        Show general amount
      </button>
    </div>
  <% end %>
</div>

  <div class="collapse" id="collapse">
    <div class="card card-body">
      Amount by category <%= @finance.name %>  is <%= @sum_amount %>
    </div>
  </div>

  <div>
    <p class="text-center"><h2>Transactions list</h2></p>
  </div>

<% @cash_transactions.each do |transaction| %>

  <div class="card">
    <div class="card-body">
    <h5 class="card-title"><%= transaction.persons_finance.person.first_name %></h5>
      <p class="card-text"><strong>Operation type:</strong> <%= transaction.persons_finance.finance.incomeOrExpence ? 'Income' : 'Expence' %></p>
        <p class="card-text"><strong>Category:</strong> <%= transaction.persons_finance.finance.name %></p>
        <p class="card-text"><strong>Amount:</strong> <%= transaction.amount %></p>

        <% if transaction.note_id.nil? %>
        <p class="card-subtitle mb-2 text-muted">Note isn't exist</p>

        <% else %>
        <div>
            <p class="card-text"><strong>Note:</strong> <%=transaction.note&.note_text%></p>
            <div>
              <%= link_to 'Edit Note', edit_note_path(transaction.note_id), class: 'btn btn-secondary' %>
              <%= link_to 'Delete Note', note_path(transaction.note_id), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
            </div>
        </div>
        <% end %>
    <div>

    </div>
  </div>
  </div>
<% end %>

app/views/finance/index.html.erb
<h1>Finances</h1>
<br>
<%= link_to 'New Finance', new_finance_path, class:'btn btn-primary' %>
<br>
<br>
<table class="table table-striped">
  <thead>
  <tr>
    <th>Name</th>

    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @finance.each do |finance| %>
    <tr>
      <td><%= finance.name %></td>
      <td><%#= link_to 'Show', person %></td>
      <td><%= link_to 'Edit', edit_finance_path(finance), class:'btn btn-secondary' %></td>
      <td><%= link_to 'Show info', finance_info_path(finance), class: 'btn btn-secondary' %></td>
      <td><%= link_to 'Delete', finance_path(finance), method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger' %></td>


    </tr>
  <% end %>
  </tbody>
</table>

<br>

app/views/finance/new.html.erb
<div class="card">
  <div class="card-header">
    <h4>Create Finance</h4>
  </div>
  <div class="card-body">


    <%= form_for :finance do |f| %>

      <div class="card-body">
        <div class="card-body">
          <div class="field form-group">
            <%= f.label :name %>
            <%= f.text_field :name,autofocus: true, class:"form-control", placeholder: 'Type' %>
            <div class="field">
              <br>
              <%= f.label 'Income' %>
              <%= f.check_box :incomeOrExpence, placeholder: 'Income' %>
            </div>
            <%= f.label 'List of person' %>
            <%#= f.collection_select(:id, current_user.person.order(:first_name),:id,:first_name, {:prompt => nil,:multiple => true}, {class:'btn btn-light dropdown-toggle'})%>
            <%= f.collection_check_boxes(:id, current_user.person.order(:first_name),:id,:first_name)%>
            <br>


          </div>

          <%= f.submit "Create finance", class: 'btn btn-secondary'%>
        </div>
      </div>
    <% end %>

  </div>
</div>

app/views/finance/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @finance.name %>
</p>
<p>
  <strong>Type:</strong>
  <%= @finance.incomeOrExpence ? 'Income' : 'Expence'%>
</p>

<%= link_to 'Edit', edit_finance_path(@finance), class: 'btn btn-secondary' %> |
<%= link_to 'Back', finances_path, class: 'btn btn-light' %>